# Generated by Django 5.0.6 on 2024-05-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Github',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('stars', models.IntegerField()),
                ('forks', models.IntegerField()),
                ('html_url', models.CharField(max_length=255)),
            ],
        ),
    ]
